name: Build Project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'
    
    - name: Install CocoaPods dependencies
      run: pod install

    - name: Resolve Swift Package Manager dependencies
      run: xcodebuild -resolvePackageDependencies -scheme PowderTrackr -project PowderTrackr.xcodeproj

    - name: Build Project
      run: xcodebuild -scheme PowderTrackr -sdk iphoneos -configuration Release build IPHONEOS_DEPLOYMENT_TARGET=16.2 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates
