name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install
          
      - name: Run Tests
        run: |
          xcodebuild test \
            -workspace PowderTrackr.xcworkspace \
            -scheme PowderTrackr \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            ONLY_ACTIVE_ARCH=YES \
            -resultBundlePath TestResults.xcresult | xcpretty --test --color --report junit
          
      - name: Parse Test Results
        run: |
          tests=$(grep -o 'testsuite tests="\d*"' TestResults.xcresult/TestSummaries.plist | grep -o '\d*')
          failures=$(grep -o 'testsuite failures="\d*"' TestResults.xcresult/TestSummaries.plist | grep -o '\d*')
          echo "Total Tests: $tests"
          echo "Failures: $failures"
          echo "Succeeded: $(($tests - $failures))"
