name: iOS Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_analyze:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create AWS Config Files
        run: |
          echo "${{ secrets.AWS_CONFIG_JSON }}" > awsconfiguration.json
          echo "${{ secrets.AMPLIFY_CONFIG_JSON }}" > amplifyconfiguration.json

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install

      - name: Clean Build
        run: |
          xcodebuild clean \
            -workspace PowderTrackr.xcworkspace \
            -scheme PowderTrackr

      - name: Run iOS Tests with Coverage
        run: |
          set -o pipefail && xcodebuild test \
            -workspace PowderTrackr.xcworkspace \
            -scheme PowderTrackr \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -enableCodeCoverage YES | xcpretty --report junit --output TestsResult.xml

      - name: Generate Coverage Report in lcov Format
        run: |
          mkdir -p sonar-reports
          llvm-cov export \
            -format=lcov \
            -instr-profile $(xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -showBuildSettings | grep -m 1 OBJROOT | cut -d " " -f 3 | xargs)/Build/Intermediates.noindex/CodeCoverage/Coverage.profdata \
            $(xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -showBuildSettings | grep -m 1 OBJROOT | cut -d " " -f 3 | xargs)/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/*.xctest/Contents/MacOS/* > sonar-reports/coverage.lcov

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=kosztid \
            -Dsonar.projectKey=kosztid \
            -Dsonar.sources=. \
            -Dsonar.javascript.lcov.reportPaths=sonar-reports/coverage.lcov \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
