name: iOS Build, Unit Tests, and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create AWS Config Files
        run: |
          echo "${{ secrets.AWS_CONFIG_JSON }}" > awsconfiguration.json
          echo "${{ secrets.AMPLIFY_CONFIG_JSON }}" > amplifyconfiguration.json

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install

      - name: Install Slather
        run: |
          sudo gem install slather

      - name: Clean Build
        run: |
          xcodebuild clean \
            -workspace PowderTrackr.xcworkspace \
            -scheme PowderTrackr

      - name: Build Project
        run: |
          xcodebuild build \
            -workspace PowderTrackr.xcworkspace \
            -scheme PowderTrackr \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            ONLY_ACTIVE_ARCH=YES | xcpretty

      - name: Run Tests with Coverage
        run: |
          set -o pipefail && xcodebuild test \
            -workspace PowderTrackr.xcworkspace \
            -scheme PowderTrackr \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -testPlan PowderTrackrTests \
            -enableCodeCoverage YES \
            ONLY_ACTIVE_ARCH=YES \
            | xcpretty --report junit --output TestsResult.xml

      - name: Generate Coverage Report with Slather
        run: |
          slather coverage \
            --sonarqube-xml \
            --output-directory . \
            --workspace PowderTrackr.xcworkspace \
            --scheme PowderTrackr \
            PowderTrackr.xcodeproj

      - name: Install SonarScanner CLI
        run: |
          brew install sonar-scanner

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=kosztid \
            -Dsonar.projectKey=kosztid_PowderTrackr \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths=sonarqube.xml
