name: iOS Build

on:
  push:
    branches:
      - main  # Set to your default branch, e.g., main or master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7  # Set this to the version used in your project

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install

    - name: Build Xcode Project
      run: |
        xcodebuild -workspace PowderTrackr.xcworkspace -scheme PowderTrackr -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=YES build
      env:
        CI: true
